name: CI/CD

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run mypy
        run: poetry run mypy .

      - name: Run Pytest
        run: docker compose --profile dev run --rm pytest -vv
