site_name: {{ cookiecutter.project_name }}
repo_name: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
watch: 
  - "mkdocs.yml"
  - "docs"
  - "htmlcov"
  - "{{ cookiecutter.module_name }}"
  - "main.py"

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  font:
    text: Calibri
    code: Inconsolata Mono
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.follow

extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js

plugins:
  - search 
  - coverage
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            show_signature_annotations: true
            show_root_toc_entry: false
            separate_signature: true
            docstring_section_style: "list"
          import:
            - https://docs.python.org/{{ ".".join(cookiecutter.python_version.split(".")[:2]) }}/objects.inv

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true

nav:
  - {{ cookiecutter.project_name }}:
    - index.md
    - coverage.md
